name: satay_meals
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^0.6.0
  firebase_messaging: 5.0.1+1 
  provider: ^3.1.0
  location: ^2.3.5
  intl: ^0.15.8 #// ^0.16.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+5
  socket_io_client: ^0.9.5
  image_picker: ^0.6.0+9 # 0.4.12+1
  dio: ^2.2.2
  path_provider: ^0.4.1
  google_maps_flutter: 0.5.21+14 #^0.5.11
  geolocator: ^5.1.5
  google_maps_webservice: ^0.0.16
  flutter_google_places: ^0.2.3
  # flutter_google_places_autocomplete: ^0.1.3
  geocoder: ^0.2.1
  firebase_auth: ^0.11.1+8
  google_sign_in: ^4.0.4
  # google_sign_in: ^4.1.4
  flutter_html: ^0.8.2

  # adhara_socket_io: ^0.1.11


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
    
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/1Stop_Consumer_favicon.png"
  image_path_android: "assets/images/1Stop_Consumer_favicon.png"
  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - assets/images/SWlogo.png
   - assets/images/fb-logo.png
   - assets/images/world.jpeg
   - assets/images/satay-vector.png
   - assets/images/cartempty.png
   - assets/images/user-unknown.jpeg
   - assets/images/driver.png
   - assets/images/cart.gif
   - assets/images/google_logo.png
  #  - assets/images/logo_one_step_delivery.jpg
  #  - assets/images/one_step_delivery_potrait.png
   - assets/images/1Stop_Consumer_favicon.png
   - assets/images/1Stop_Consumer_Splash_Screen.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Bold.ttf
        - asset: assets/fonts/Play-Regular.ttf
          weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
